name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.yogesh3096 }}
        password: ${{ secrets.qwertyQ123 }}

    - name: Build Docker image
      run: docker build -t yogesh3096/trial123:latest .

    - name: Push Docker image
      run: docker push yogesh3096/trial123:latest

    # - name: Deploy to AWS
    #   uses: aws-actions/elastic-beanstalk-deploy@v3
    #   with:
    #     environment-name: your-environment-name
    #     app-name: your-app-name
    #     version-label: ${{ github.sha }}
    #     region: your-aws-region
    #     access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
